#ifndef ERROR_NO_H_
#define ERROR_NO_H_

enum{
    SUCCESS = 0, 
    INVALID_PORT_NUMBER, 
    SOCKET_CREATE_ERROR,
    INIT_LINGER_ERROR,
    SOCKET_SET_OPTION_ERROR,
    SOCKET_BIND_ERROR,
    SOCKET_LISTEN_ERROR,
    SOCKET_ACCEPT_ERROR,
    READ_SIGNAL_ERROR,
    FCNTL_FAILED,
    EPOLL_CREATE_FAILED,
    EPOLL_ADD_INVALID_FD,
    EPOLL_ADD_FAILED,
    EPOLL_MOD_INVALID_FD,
    EPOLL_MOD_FAILED,
    EPOLL_DEL_INVALID_FD,
    EPOLL_DEL_FAILED,
    EPOLL_WAIT_FAILED,
    INVALID_MAX_EVENTS_NUMBER
};

#endif